### ISSUE TITLE
Api Documentation Issue

### ISSUE THREAD

**Issue by ihsonnet** [Mamun-swe/storexapi#2]
Great vai! It was an on demand initiative for frontend developers ❤️

Maybe using of Api Documentation Tool like SwaggerHub or UI will be more helpfull for users.

**Comment by mamun-swe** [comment]
Thanks for your valuable comment, ASAP I'll attached postman documentation and sawgger UI will add to next version.

**Comment by ihsonnet** [comment]
Best wishes vai.
